# Site settings
title: Noah Bello
email: Noahbello007@gmail.com
description: > # keep this and put description below
  Programmer and Designer
url: https://NoahBello.github.io
linkedin_url: https://www.linkedin.com/in/noah-bello-572a51212/
footer_text: "This site uses <a href='https://github.com/gamingportfolio/urban-theme-portfolio'>urban-theme (portfolio)</a>."

# Build settings
markdown: kramdown
permalink: pretty
